### ISSUE TITLE
Add a validate function

### ISSUE THREAD

**Issue by tetienne** [AppDaemon/appdaemon#1024]
For some of my application taken various parameters, I use to validate them during the init;

```python
import json
from appdaemon.adbase import ADBase
import voluptuous as vol
from constants import APP_MIN_SCHEMA

APP_SCHEMA = APP_MIN_SCHEMA.extend(
    {
        vol.Required("name"): str,
        vol.Required("light"): str,
        vol.Required("switch"): str,
        vol.Required("unique_id"): str,
    }
)


class MyApp(ADBase):
    def initialize(self):
        self.args = APP_SCHEMA(self.args)
        self.hass = self.get_plugin_api("HASS")
        self.mqtt = self.get_plugin_api("MQTT")
        self.light = self.args["light"]
        self.switch = self.args["switch"]

        # do something...
```

This way I have no surprise at runtime if by mistake I forgot something. Using voluptuous, I can also set default value.

It would be really nice to have a method call just before _initialize_ to test the parameters given to the app. If the returned value is true, you can initialize the app, else log an error message and don't initialize the app.

The above code will become:

```python
import json
from appdaemon.adbase import ADBase
import voluptuous as vol
from constants import APP_MIN_SCHEMA

APP_SCHEMA = APP_MIN_SCHEMA.extend(
    {
        vol.Required("name"): str,
        vol.Required("light"): str,
        vol.Required("switch"): str,
        vol.Required("unique_id"): str,
    }
)


class MyApp(ADBase):
    def initialize(self):
        self.hass = self.get_plugin_api("HASS")
        self.mqtt = self.get_plugin_api("MQTT")
        self.light = self.args["light"]
        self.switch = self.args["switch"]

        # do something...

    def validate(self):
        try:
            self.args = APP_SCHEMA(self.args)
            return True
        except MultipleInvalid as e:
            return False
```

It will also ease the application sharing.

What do you think?

**Comment by danhei** [comment]
I had a similar problem and solved it like this:
```python
class MyApp(ADBase):
    def initialize(self):
        if not self.validate():
            # log errors ...
            # stop app ...
            return
```

**Comment by ReneTode** [comment]
it would be very complicated to implement such a thing as OPTION in AD.
i use app configs like this:
```
licht_HKEKGA_kelder_start:
  module: actions
  class: actions
  if:
    - sensor.kellertime: {"new_state": "ja","delay": 14400}
  do_first:
    - switch.woonkamer_verlichting: {"value": "off", "delay": 610}
    - switch.eetkamer_verlichting: {"value": "off", "delay": 600}
    - switch.woonkamer_tv: {"value": "off", "delay": 660}
    - switch.hoofdkeuken_uit: {"value": "on", "delay": 840}
  do_after_some_delay:
    - light.traplicht_beneden: {"value": "on", "preset_hel"}
    - switch.woonkamer_verlichting: {"value": "on", "delay": 900}
    - switch.eetkamer_verlichting: {"value": "on", "delay": 910}
    - switch.gang_verlichting: {"value": "on", "delay": 920}
    - switch.woonkamer_tv: {"value": "on", "delay": 930}
    - switch.hoofdkeuken_sfeer: {"value": "on", "delay": 940}
  hold_for:
    - sensor.keller_gesloten: "ja"
    - switch.rene_ziek: "on"
    - switch.marjolijn_ziek: "on"
    - switch.olinde_ziek: "on"
  plugin: NONE
```
which would give me a very complicated validation.
so i wouldnt want to use it.

AD would need to check
if the user wants to use validation, if the validation is setup correctly and if the validation is correct.

but you can create general functions and use get_app()

so doing it like danhei does is very easy.
