### ISSUE TITLE
weather widget displays entity not found...

### ISSUE THREAD

**Issue by branitelj91** [AppDaemon/appdaemon#1032]
Ok people!
Here I am having issue with weather widget. 
Apparently, (being new to this part of HASSIO integrations), I have not account with darksky service. 
As alternative to this, I have opened several accounts, (weatherbit, accuweather, some others as well), but each one displays same info within widget, but fully workable in HASSIO dashboard.
If entity declared, (no matter which platform), I have "entity not found...", (as displayed in screenshot). If I remove this within declaration the message  says "entity not found: undefined". 
Same issue is if I put this in layout. Simple message says same message. 
(please, disregard "display_title..." as this is my faulty try. 

Any hint. 
What is wrong in my config.

**Comment by ReneTode** [comment]
the weather widget was designed to work with dark sky long time ago.
home assistant and dark sky have changed a lot over time.
thats why the default settings dont work.
if you declare sensors like you do you need to declare correct.
this is the example from the docs:
```
sample_weather:
  widget_type: weather
  title: Today
  show_forecast: 1
  prefer_icons: 1
  forecast_title: Tomorrow
  sensors:
    icon: sensor.dark_sky_icon
    temperature: sensor.dark_sky_temperature
    apparent_temperature: sensor.dark_sky_apparent_temperature
    humidity: sensor.dark_sky_humidity
    precip_probability: sensor.dark_sky_precip_probability
    precip_intensity: sensor.dark_sky_precip_intensity
    precip_type: sensor.dark_sky_precip
    pressure: sensor.dark_sky_pressure
    wind_speed: sensor.dark_sky_wind_speed
    wind_bearing: sensor.dark_sky_wind_bearing
    forecast_icon: sensor.dark_sky_icon_1
    forecast_temperature_min: sensor.dark_sky_daily_low_temperature_1
    forecast_temperature_max: sensor.dark_sky_daily_high_temperature_1
    forecast_precip_probability: sensor.dark_sky_precip_probability_1
    forecast_precip_type: sensor.dark_sky_precip_1
```
in weather2 you got entity, which isnt a part that belongs there.
you can replace all sensors in the example with EXISTING entities.

when you get "entity not found" then you did use an entity that doesnt exist in your home assistant.
