### ISSUE TITLE
Blank Widgets

### ISSUE THREAD

**Issue by c0nt4x** [AppDaemon/appdaemon#1033]
I've created my first dashboard using appdaemon 4 Home Assistant add on. However, when I select the dashboard all widgets, except for the clock are blank. Can you advise please. My code and result are below:
```
##
## Main arguments, all optional
##
title: Main Panel
widget_dimensions: [120, 120]
widget_size: [1, 1]
widget_margins: [5, 5]
columns: 8
global_parameters:
    use_comma: 0
    precision: 1
    use_hass_icon: 1
layout:
    - clock.clock (2x1), sensor.sensor_kitchen_temperature, sensor.sensor_stairs_temperature, sensor.sensor_landing_temperature
    - person.martin, person.rachel, weather.weather (2x1)
    - scene.sunset_lounge, scene.sunset_bedroom, light.office_lamp (2x1)
    - group.airfresheners, switch.bfb134910d97c838b5xzvm, switch.bf4766981e758041f6nvfz, sun.sun
```
![Untitled](https://user-images.githubusercontent.com/70321584/91712318-6cfb3d80-eb7f-11ea-9928-1b1bdeb2c2eb.png)
