### ISSUE TITLE
No listener on 5050 

### ISSUE THREAD

**Issue by JC-Mac** [AppDaemon/appdaemon#1034]
Hi everyone,

I have used hadashboard for a few years.  Recently, my dashboards stopped working.   I think the inital cause was an expired certificate on my domain ... however in the troubleshooting process, I upgraded appdaemon to the most recent version and seem to have broken my setup.  when I start appdaemon, I get nothing listening on port 5050.  Other than that, startup seems to work fine (connects successfully to HA)

I run HA on the same machine, and use nginx to reverse proxy https://dash.mydomain.com to the 5050 port.

My config and start log is below ... (I've left in some commented attempts at fixing this)
```

appdaemon:
  disable_apps: 1
  plugins:
    HASS:
      type: hass
      ha_url: https://ha.mydomain.com
      token: mytoken
      delay: 30
#    hadashboard:
#      dashboard_dir: /home/homeassistant/.homeassistant/appdaemon/conf/dashboards

  latitude: 44.379970
  longitude: -73.533408
  elevation: 62
  time_zone: America/Toronto

hadashboard:
  dashboard_dir: /home/homeassistant/.homeassistant/appdaemon/conf/newdashes
  dash_url: https://dash.mydomain.ca:5050
#  dash_url: http://dash.mydomain.ca:5050  
#  dash_url: http://dash.mydomain.ca
#  dash_url: http://dash.mydomain.ca:5018
#  dash_url: https://dash.mydomain.ca:5018 
#  accessfile: /var/log/dash_access
  dash_ssl_certificate: /etc/letsencrypt/live/mydomain.com/cert.pem
  dash_ssl_key: /etc/letsencrypt/live/mydomain.com/privkey.pem
  dash_password: !secret dash_key
#  compile_on_start: 1
logs:
  main_log:
    filename: /home/homeassistant/.homeassistant/appdaemon/conf/appdaemon.log
    logsize: 100000
    log_generations: 3
  access_log:
    filename: /home/homeassistant/.homeassistant/appdaemon/conf/access.log
    logsize: 100000
    log_generations: 3
  error_log:
    filename: /home/homeassistant/.homeassistant/appdaemon/conf/error.log
    logsize: 100000
    log_generations: 3
```

The log after a restart:

2020-09-05 08:30:06.071184 INFO AppDaemon: SIGTERM Received
2020-09-05 08:30:06.071536 INFO AppDaemon: AppDaemon is shutting down
2020-09-05 08:30:06.111835 INFO HASS: Disconnecting from Home Assistant
2020-09-05 08:30:06.887524 INFO AppDaemon: Saving all namespaces
2020-09-05 08:30:06.887806 INFO AppDaemon: AppDaemon is stopped.
2020-09-05 08:30:08.276089 INFO AppDaemon: AppDaemon Version 4.0.4 starting
2020-09-05 08:30:08.276333 INFO AppDaemon: Python version is 3.6.9
2020-09-05 08:30:08.276538 INFO AppDaemon: Configuration read from: /home/homeassistant/.homeassistant/appdaemon/conf/appdaemon.yaml
2020-09-05 08:30:08.276741 INFO AppDaemon: Added log: AppDaemon
2020-09-05 08:30:08.276949 INFO AppDaemon: Added log: Error
2020-09-05 08:30:08.277155 INFO AppDaemon: Added log: Access
2020-09-05 08:30:08.277360 INFO AppDaemon: Added log: Diag
2020-09-05 08:30:08.323927 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-09-05 08:30:08.341545 INFO HASS: HASS Plugin Initializing
2020-09-05 08:30:08.341777 INFO HASS: HASS Plugin initialization complete
2020-09-05 08:30:08.342197 INFO AppDaemon: HTTP is disabled
2020-09-05 08:30:08.368539 INFO HASS: Connected to Home Assistant 0.97.2
2020-09-05 08:30:08.380616 INFO AppDaemon: App 'hello_world' added
2020-09-05 08:30:08.382704 INFO AppDaemon: Found 1 total apps
2020-09-05 08:30:08.383142 INFO AppDaemon: Starting Apps with 1 workers and 1 pins
2020-09-05 08:30:08.407817 INFO HASS: Evaluating startup conditions
2020-09-05 08:30:08.411870 INFO HASS: All startup conditions met
2020-09-05 08:30:08.460134 INFO AppDaemon: Got initial state from namespace default
2020-09-05 08:30:10.389437 INFO AppDaemon: Scheduler running in realtime
2020-09-05 08:30:10.400904 INFO AppDaemon: Adding /home/homeassistant/.homeassistant/appdaemon/conf/apps to module import path
2020-09-05 08:30:10.401435 INFO AppDaemon: App initialization complete
