### ISSUE TITLE
register_service / call_service not working?

### ISSUE THREAD

**Issue by rr326** [AppDaemon/appdaemon#1053]
I can't get `register_service` / `call_servic`e to work and yet I *think* I'm doing it right. I'm on the latest release in the master branch (f32ebfb87a1cac0e0fcaa08e9b1725b68a7aa56a), running in a container. AD seems to be working fine other than this.

### test_service.yaml
```yaml
serviceprovider:
  module: test_services
  class: ServiceProvider

servicecaller:
  module: test_services
  class: ServiceCaller
```

### test_services.py
```python
import hassapi as hass
import re


class ServiceProvider(hass.Hass):
    def initialize(self):
        self.log("ServiceProvider Initialize")
        self.log(
            f'"service_provider" in list_services - Before? Matched: {self.list_matched()}'
        )
        self.register_service("service_provider/on", self.cb_on)
        self.log(
            f'"service_provider" in list_services - After? Matched: {self.list_matched()}'
        )

    def cb_on(self, *args, **kwargs):
        self.log(f'Service "ON" called. args: ({args}). kwargs: ({kwargs})')

    def list_matched(self):
        return [
            service
            for service in self.list_services()
            if re.match(".*service_provider.*", str(service))
        ]


class ServiceCaller(hass.Hass):
    def initialize(self):
        self.log("ServiceCaller Initialize - waiting 2 seconds")
        self.run_in(self.cb_call_service, 2)

    def cb_call_service(self, *args, **kwargs):
        self.log(
            f'ServiceCaller - calling "service_provider/on. args: ({args}). kwargs: ({kwargs})"'
        )
        self.call_service("service_provider/on")
        self.log('ServiceCaller - called "service_provider/on"')

```

### appdaemon.log
```
2020-10-08 05:30:11.617274 INFO serviceprovider: ServiceProvider Initialize
2020-10-08 05:30:11.621597 INFO serviceprovider: "service_provider" in list_services - Before? Matched: []
2020-10-08 05:30:11.625548 INFO serviceprovider: "service_provider" in list_services - After? Matched: [{'namespace': 'default', 'domain': 'service_provider', 'service': 'on'}]
2020-10-08 05:30:11.636631 INFO servicecaller: ServiceCaller Initialize - waiting 2 seconds
2020-10-08 05:30:14.026803 INFO servicecaller: ServiceCaller - calling "service_provider/on. args: (({'__thread_id': 'thread-5'},)). kwargs: ({})"
2020-10-08 05:30:14.045739 WARNING HASS: Error calling Home Assistant service default/service_provider/on
2020-10-08 05:30:14.048000 WARNING HASS: Code: 400, error: 400: Bad Request
2020-10-08 05:30:14.056555 INFO servicecaller: ServiceCaller - called "service_provider/on"
```

### docker_compose.yaml - just in case
```yaml
version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /home/pi/dev/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
  appdaemon:
    container_name: appdaemon
    restart: "unless-stopped"
    image: appdaemon:latest 
    volumes:
      - ../homeassistant/appdaemon/conf:/conf
      - ../homeassistant/appdaemon/logs:/logs
    depends_on:
      - homeassistant
    network_mode: host
    environment:
      - AD_LOG_MAIN=/logs/appdaemon.log
      - AD_LOG_ACCESS=/logs/access.log
      - AD_LOG_ERROR=/logs/error.log
      - AD_LOG_DIAG=/logs/diag.log


```
