### ISSUE TITLE
Send HTML email through HA notify

### ISSUE THREAD

**Issue by GigaTech** [AppDaemon/appdaemon#1070]
Hi, I am trying to send a HTML email through HA notify service

This works
`self.call_service('notify/email_info', title = notification_title, message = notification_body)`

This also works
`self.notify(notification_body, title = notification_title, name = 'email_info')`

but both sends out a plain text email message. is there any way to get to the built in html message body format

This does not work
`self.call_service('notify/email_info', title = notification_title, html = notification_body)`

Here are the HA docs
[https://www.home-assistant.io/integrations/smtp/](https://www.home-assistant.io/integrations/smtp/)

automations.yaml to send html email:
```
- alias: x_email
  # Send email every 30 seconds if 'testing' button = on
  trigger:
    - platform: time_pattern
      seconds: /30
  condition:
    - condition: state
      entity_id: input_boolean.testing
      state: "on"

  action:
    - service: notify.email_info
      data:
        message: "Your message goes here"
        title: "Custom subject"
        html: >
          <!doctype html>
          <html lang="en" xmlns="http://www.w3.org/19...
```

which works.

Thanks
