### ISSUE TITLE
HaDashboard - Icons no longer appearing on HA 0.117.5

### ISSUE THREAD

**Issue by borpin** [AppDaemon/appdaemon#1074]
Just upgraded to HA 0.117.5, AppDaemon 0.3.1 via the Addon.

I have used a switch definition in the HaDashboard to turn on lights and groups of lights (I don't like the group widget as I cannot turn off the dimmer controls).

![image](https://user-images.githubusercontent.com/1322749/98785145-10749400-23f4-11eb-8670-633c40df0738.png)

As is seen, the Icon no longer appears for the group. Prior to 0.117.5 (0.116.x) it worked fine. Nothing I can see in the logs. It still works for a single light entity.

I have tried the 'groups' widget and nothing there either.

```
lamps:
    widget_type: switch
    title: Lamps
    entity: light.lamps
    title_style: "font-size: 150%;"
    icon_style: "position: unset; top: unset;"
    icon_style_inactive: "color: grey"
    icon_style_active: "color: yellow"
    icon_on: fas-lightbulb
    icon_off: fas-lightbulb
```

where `light.lamps` is defined with the `group` platform in 'light.yaml` as

```
- platform: group
  name: Lamps
  entities:
    - light.hall_lamp
    - light.sunroom_side_lamp
    - light.sunroom_standing_lamp
```

This still works from the Lovelace dashboard.
