### ISSUE TITLE
Rss feed error

### ISSUE THREAD

**Issue by pckeller29** [AppDaemon/appdaemon#1076]
Hi
I've recently upgraded from Appdaemon 4.0.1 to 4.0.5.
In my dashboard, I'm using two rss feeds which used to work fine.
Actually, when I started appdaemon, the two feeds were always blank and got populated a few minutes later. this behavior was not really a problem since I didn't restart appdaemon often and it was not meant to.

The issue I'm facing now is an error in my browser console when I try to display those feeds. This cause almost all my buttons in the dashboard to loose their icons.
After a few minutes though, the rss feed is correctly displayed but still no icons on the other buttons (switch buttons, the navigation ones keep theirs).

Here is an extract of my appdaemon.yaml:
```
hadashboard:
  api_key: !secret appdaemon_key
  dashboard_dir: /home/appdaemon/conf/dashboards
  rss_feeds:
    - feed: https://www.nextinpact.com/rss-complet/177047/2cf4240d839db0e17784e3de3971ed931c1bfae923e8c8e3790c59da3e2025da
      target: rss.nxi
    - feed: https://www.lalsace.fr/rss
      target: rss.news
  rss_update: 300 
secrets: /home/appdaemon/conf/secrets.yaml
```

An extact of the dashboard:
```
nxi_rss:
    widget_type: rss 
    entity: rss.nxi
    title: "NextINpact"
    title_style: "font-size: 150%;"
    text_style: "font-size: 200%;"
    interval: 10

news_rss:
    widget_type: rss 
    entity: rss.news
    title: "LAlsace"
    title_style: "font-size: 150%;"
    text_style: "font-size: 200%;"
    interval: 10
```

Here is what I get in my browser console (Firefox or Vivaldi):
```
application.js:1550 Uncaught TypeError: Cannot read property 'state' of undefined
    at show_next_story (application.js:1550)
    at set_value (application.js:1544)
    at Object.OnStateAvailable [as initial] (application.js:1532)
    at baserss.WidgetBase.set_state (dashboard.js:287)
    at DashStream.populate_dash (dashboard.js:83)
    at WSStream.Stream.ad_on_message [as on_message] (stream.js:115)
    at a.WSStream.ws_on_message [as onmessage] (stream.js:327)
    at HTMLDivElement.<anonymous> (reconnecting-websocket.min.js:1)
    at WebSocket.h.onmessage (reconnecting-websocket.min.js:1)
DevTools failed to load SourceMap: Could not load content for http://domos5.lan.pc:5050/css/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for http://domos5.lan.pc:5050/css/dist/jquery.gridster.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

And the corresponding code:
```
    function show_next_story(self)
    {
        var stories = self.entity_state[parameters.entity].state.feed.entries;
        self.set_field(self, "text", stories[self.story].title);
        if ("show_description" in self.parameters && self.parameters.show_description === 1)
        {
            if ("summary" in stories[self.story])
            {
                self.set_field(self, "description", stories[self.story].summary)
            }
            if ("description" in stories[self.story])
            {
                self.set_field(self, "description", stories[self.story].description)
            }
        }
        self.story = self.story + 1;
        if ((self.story >= stories.length) || ("recent" in parameters && self.story >= parameters.recent))
        {
            self.story = 0;
        }
    }
}

```
The failing line is the first one:
`        var stories = self.entity_state[parameters.entity].state.feed.entries;`

Of course I could live without the feeds but this leaves 2 big blanks in my dashboard and I liked to have them.
Again, this issue started in 4.0.3 and is still there in 4.0.5. It worked fine in 4.0.1.

Any idea ?
Thanx
