### ISSUE TITLE
Enable building for Raspberry Pi Docker

### ISSUE THREAD

**Issue by rr326** [AppDaemon/appdaemon#1087]
In order to get AD to build for my raspberry pi, I had to do the following. (And I am not sure this is the minimum sufficient or best method.)

### New: pyproject.toml
```toml
# pyproject.toml

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"
```

### Updated: Dockerfile
```
# Install dependencies
RUN apk add --no-cache gcc g++ libffi-dev musl-dev  \
    && pip install --no-cache-dir .
```

Becomes:
```
# Additional dependencies - line 2
RUN apk add --no-cache gcc g++ libffi-dev musl-dev  \
    libffi-dev libressl-dev python3-dev py-pip\
    && pip install --no-cache-dir .
```
If these wouldn't be a problem upstream, then I could issue a PR. If not appropriate, I'll just leave in my fork.
