### ISSUE TITLE
crashes on raspi docker

### ISSUE THREAD

**Issue by hanneshier** [AppDaemon/appdaemon#1093]
I've followed [this](https://appdaemon.readthedocs.io/en/latest/INSTALL.html#raspbian) instructions to build appdaemon locally on my raspberry pi. But the container always crashes when I try to start it.

logs:
```
docker-compose up
Creating network "appdaemon_default" with the default driver
Creating appdaemon ... done
Attaching to appdaemon
appdaemon    | 2020-12-09 22:26:22.167836 INFO AppDaemon: AppDaemon Version 4.0.6 starting
appdaemon    | 2020-12-09 22:26:22.169292 INFO AppDaemon: Python version is 3.8.6
appdaemon    | 2020-12-09 22:26:22.169860 INFO AppDaemon: Configuration read from: /conf/appdaemon.yaml
appdaemon    | 2020-12-09 22:26:22.171387 INFO AppDaemon: Added log: AppDaemon
appdaemon    | 2020-12-09 22:26:22.172424 INFO AppDaemon: Added log: Error
appdaemon    | 2020-12-09 22:26:22.173569 INFO AppDaemon: Added log: Access
appdaemon    | 2020-12-09 22:26:22.174207 INFO AppDaemon: Added log: Diag
appdaemon    | 2020-12-09 22:26:22.175210 ERROR AppDaemon: time_zone not specified in appdaemon.cfg
appdaemon    | 2020-12-09 22:26:22.176461 ERROR AppDaemon: latitude not specified in appdaemon.cfg
appdaemon    | 2020-12-09 22:26:22.177212 ERROR AppDaemon: longitude not specified in appdaemon.cfg
appdaemon    | 2020-12-09 22:26:22.177871 ERROR AppDaemon: elevation not specified in appdaemon.cfg
```

docker-compose.yml
```
version: "3.3"
services:
  appdaemon:
    container_name: appdaemon
    image: appdaemon:latest
    ports:
      - "5050:5050"
    restart: always
    environment:
      HA_URL: localhost:8123
      TOKEN: <TOKEN>
      DASH_URL: http://localhost:5050
    volumes:
      - ./conf:/conf
```

The same happens when I start it without docker-compose and use
```
docker run --name=appdaemon -d -p 5050:5050 \
  --restart=always \
  -e HA_URL="<Your HA_URL value>" \
  -e TOKEN="<your TOKEN value>" \
  -e DASH_URL="http://$HOSTNAME:5050" \
  -v /home/pi/appdaemon/conf:/conf \
  appdaemon:latest
```

Does anyone has an idea why this happens?
