### ISSUE TITLE
MQTT over SSL: SSL routines:ACCEPT_SR_CLNT_HELLO:unknown protocol

### ISSUE THREAD

**Issue by thd6n75** [AppDaemon/appdaemon#1161]
I run Mosquitto in a docker container and I use SSL.  I have various clients connecting to it successfully all via MQTT + SSL on port 8883, including homeassistant, MQTT explorer, and zigbee2mqtt.  However, when I setup the MQTT plugin in appdaemon, appdaemon produces these logs:

```
2021-02-14 16:56:57.286927 CRITICAL MQTT: MQTT Client Disconnected Abruptly. Will attempt reconnection
2021-02-14 16:57:00.138298 CRITICAL MQTT: MQTT Plugin Stopped Unexpectedly
2021-02-14 16:57:00.138484 CRITICAL MQTT: Unable to reinitialize MQTT Plugin, will keep trying again until complete
```

This repeats. Appdaemon never connects to my MQTT broker.  On the Mosquitto end, here's the error produced when appdaemon tries to connect:

```
1613339589: New connection from xxxxx:38399 on port 8883.
1613339589: OpenSSL Error[0]: error:140260FC:SSL routines:ACCEPT_SR_CLNT_HELLO:unknown protocol
1613339589: Client <unknown> disconnected: Protocol error.
```

Here's appdaemon's MQTT config:

```
    MQTT:
       type: mqtt
       namespace: mqtt
       verbose: True
       client_host: !secret mqtt_host
       client_port: !secret mqtt_port
       client_user: !secret appdaemon_mqtt_user
       client_password: !secret appdaemon_mqtt_passwd
       tls_version: auto
       verify_cert: True
       event_name: MQTT_EVENT
       force_start: True
```

This behavior is the same for all values of `tls_version`:  `auto`, `1.0`, `1.1`, `1.2`

I'm using the `acockburn/appdaemon:4.0.5` docker image for appdaemon and the `eclipse-mosquitto:2.0.7` image for mosquitto.
