### ISSUE TITLE
Icon widget broken by 4.0.6

### ISSUE THREAD

**Issue by lancasterJ** [AppDaemon/appdaemon#1234]
Icon widget stopped displaying the icon and state text when upgraded to 4.0.6.  Before updating to 4.0.6 this code

```
garbage:
    widget_type: icon
    entity: sensor.garbage
    title: Garbage
    title2: collection
    state_text: 1
    icons:
      "today":
        icon: mdi-delete-circle
        style: "color: blue"
      "tomorrow":
        icon: mdi-delete-restore
        style: "color: black"
      "default":
        icon: mdi-delete-empty
        style: "color: white"
```

produced 

![image](https://user-images.githubusercontent.com/63460573/112718576-dfe94e80-8eeb-11eb-94ef-e7e54bda85d7.png)

After the upgrade the following is displayed

![image](https://user-images.githubusercontent.com/63460573/112718594-01e2d100-8eec-11eb-9cc0-2faf5e2e1cd9.png)

Commenting out the "default" section results in the state text being displayed, but not the icon.

```
garbage:
    widget_type: icon
    entity: sensor.garbage
    title: Garbage
    title2: collection
    state_text: 1
    icons:
      "today":
        icon: mdi-delete-circle
        style: "color: blue"
      "tomorrow":
        icon: mdi-delete-restore
        style: "color: black"
      # "default":
        # icon: mdi-delete-empty
        # style: "color: white"
```

![image](https://user-images.githubusercontent.com/63460573/112718645-4b332080-8eec-11eb-9ff6-891c85ad46af.png)
