### ISSUE TITLE
Relative URLs in the config

### ISSUE THREAD

**Issue by filmgarage** [AppDaemon/appdaemon#1386]
I run AppDaemon on docker together with the installation of Home Assistant on another docker container.

For the two to work together I have to 'hard code' the IP number for my HA instance:
```
---
secrets: /config/secrets.yaml
appdaemon:
  latitude: 12
  longitude: 5
  elevation: 69
  time_zone: Europe/Paris
  plugins:
    HASS:
      type: hass
      ha_url: http://192.1681.25:8123
      token: !secret appdaemontoken
http:
  url: http://127.0.0.1:5050
admin:
api:
hadashboard:
  dash_url: http://192.168.1.25:5050
```
Is it possible to put some "relative" links in stead of the fixed IP addresses?

`localhost`  does not seem to work...

Maybe I can put poll the local IP with home assistant and use that sensor to provide the IP address?
I need this to be able to take the machine around to other locations without resetting this address all the time.
