### ISSUE TITLE
Skipping Token with trusted_networks

### ISSUE THREAD

**Issue by BenediktAllendorf** [AppDaemon/appdaemon#1410]
Hey everyone,

I am working on an easy (dev) setup using docker-compose. For that, I would like to have the app-daemon connect to my home-assistant instance **without configuring anything more (i.e., the access token)**.

I thought this might be possible with the `trusted_networks`-configuration, but I'm getting only errors indicating the authorization did not work:
AD: `WARNING HASS: Disconnected from Home Assistant, retrying in 5 seconds`
HA: `Disconnected: Did not receive auth message within 10 seconds`

Access without login does work in my browser, though.

So my question is: should this work (given the configuration is correct)? If not, is this a limitation of HA or AD (and would it technically be possible to implement such a thing)?

---
I have the following configuration in HA:
```YAML
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 172.0.0.0/8
        - 127.0.0.1
        - ::1
    - type: homeassistant
```

AppDaemon:
```YAML
appdaemon:
[...]
  plugins:
    HASS:
      type: hass
      ha_url: http://homeassistant:8123
      token:
http:
  url: http://localhost:5050
```

And my docker-compose looks like this:
```YAML
[...]
homeassistant:
  container_name: homeassistant
  image: homeassistant/home-assistant
  volumes:
    - ${DATA_PATH}/homeassistant:/config
    - /etc/localtime:/etc/localtime:ro
  restart: unless-stopped
  ports:
    - "8123:8123"
  privileged: true

appdaemon:
  container_name: appdaemon
  restart: unless-stopped
  image: acockburn/appdaemon:latest
  privileged: true
  depends_on:
    - homeassistant
  environment:
    - HA_URL=http://homeassistant:8123
    - DASH_URL=http://localhost:5050
  ports:
    - "5050:5050"
  volumes:
    - ${DATA_PATH}/appdaemon:/conf
 ```

**Comment by ReneTode** [comment]
im not sure if HA allows it at all to work completely without tokens nowadays (there are no tokens setup at all in your HA?)
but if its allowed i think the reason could be that you did provide the keyword token.
```
   HASS:
      type: hass
      ha_url: http://homeassistant:8123
      token:
```
is the same as
```
   HASS:
      type: hass
      ha_url: http://homeassistant:8123
      token: ""
```
which is different then providing no token at all which would be
```
   HASS:
      type: hass
      ha_url: http://homeassistant:8123
```
