### ISSUE TITLE
Camera widget - entity_picture doesn't seem to work after upgrade from AD3 >- AD4.

### ISSUE THREAD

**Issue by MarkHofmann11** [AppDaemon/appdaemon#1417]
I just recently upgraded from AD 3 -> AD 4, and noticed my entity_picture under the camera widget no longer works.  It is pointing to a local URL (which is actually BlueIris).  It just display a white/blank box.

Here is the config:
````
front_yard_camera:
    widget_type: camera
    widget_style: "background-color: mediumblue"
    title: Front Yard Camera
    refresh: 11
    frame_style: ""
    entity: camera.blueiris_front_yard_camera
#    base_url: http://homeassistant:8123
    entity_picture: "http://blueiris/image/cam1"
````

Using the base URL works, but it seems to make the box flash each time it updates which didn't happen when using the entity_picture method.

**Comment by ReneTode** [comment]
do you have a custom widget?
because i cant remember that we ever had entity_picture in the camera widget.

use
```
front_yard_camera:
    widget_type: camera
    widget_style: "background-color: mediumblue"
    title: Front Yard Camera
    base_url: http://homeassistant:8123
    stream: "on"
```
and refresh is only there for tablets and cams that lose connection at some point, or still image cameras.

**Comment by MarkHofmann11** [comment]
Thank you.  I don't think it was a custom widget, but I set all that up years ago and it was running on an old version of Appdaemon (older 3x version).  I used that when the legacy API method in HA was disabled.

Anyway, should I see what appears to be updates when stream: "on" with no refresh entry?  When I test it, I get what appear to be refreshes for all the cameras at certain intervals even with no refresh set.  I tried via PC web browser and Samsung android tablet.  The old way it was grabbing still pictures ever 11 seconds and it wasn't obvious when there was a refresh.  It just updated the picture vs the entire picture disappearing and then updating.

**Comment by MarkHofmann11** [comment]
I just updated the config to your example and it seems to do random refreshes on all the camera feeds.  I tried with no refresh in the config and adding it with a setting of 0.  

What you see is each camera image will disappear in a row and then reappear in the same order (like a refresh).

**Comment by ReneTode** [comment]
no there is no picture widget that refreshes that i know of.

but if you have the cam in HA setup as still picture and not a stream then your config should be different.
```
front_yard_camera:
    widget_type: camera
    widget_style: "background-color: mediumblue"
    title: Front Yard Camera
    base_url: http://homeassistant:8123
```
this should refresh the still image every 10 seconds.
with resfresh: 11 it should be every 11 seconds.
but thats what you already had and that flashes.

the camera widget is for HA cameras only.
if you do want a direct link to a cam stream you can use the iframe widget, but it doesnt do auto resfrehes, so the page you use should update.

i think you should change settings in HA or blueiris to get a normal stream, or else you maybe could try to find the widget from AD 3, use it as custom widget, and maybe you will need to make some small changes.

if you want help with that i am available on our discord channel.
