### ISSUE TITLE
Changing log_level from INFO to DEBUG is ignored 

### ISSUE THREAD

**Issue by skannea** [AppDaemon/appdaemon#1464]
Changing log_level from INFO to DEBUG in apps.yaml makes the app reload but without changing the log level.
Changing from DEBUG to INFO works.
 

```
import appdaemon.plugins.hass.hassapi as hass 

class Test20(hass.Hass):  

  def initialize(self):   
    self.log( 'log level is %s', self.args.get('log_level', 'NONE'), level='WARNING')
    self.log('debug',   level='DEBUG')
    self.log('info',    level='INFO')
    self.log('warning', level='WARNING')

  def terminate(self):  
    self.log('terminate', level='WARNING') 

```
```
test20a:
 module: test20   
 class: Test20  
 log_level: DEBUG

test20b:
 module: test20   
 class: Test20  
 log_level: INFO

```
After restarting AD, a correct logging is produced:
```
2022-01-14 23:10:33.087963 WARNING test20b: warning
2022-01-14 23:10:33.085253 INFO test20b: info
2022-01-14 23:10:33.079838 WARNING test20b: log level is INFO
2022-01-14 23:10:33.066920 WARNING test20a: warning
2022-01-14 23:10:33.064343 INFO test20a: info
2022-01-14 23:10:33.061996 DEBUG test20a: debug
2022-01-14 23:10:33.059115 WARNING test20a: log level is DEBUG

```
The log levels are changed and apps.yaml is saved and apps are reloaded.
```
test20a:
 module: test20   
 class: Test20  
 log_level: INFO

test20b:
 module: test20   
 class: Test20  
 log_level: DEBUG

```
In the log the DEBUG logging from test20b is missing. 
```
2022-01-14 23:15:32.784931 WARNING test20b: warning
2022-01-14 23:15:32.780966 INFO test20b: info
2022-01-14 23:15:32.770323 WARNING test20b: log level is DEBUG
2022-01-14 23:15:32.755957 WARNING test20a: warning
2022-01-14 23:15:32.752655 INFO test20a: info
2022-01-14 23:15:32.744986 WARNING test20a: log level is INFO
2022-01-14 23:15:32.720869 INFO AppDaemon: Initializing app test20b using class Test20 from module test20
2022-01-14 23:15:32.708123 INFO AppDaemon: Initializing app test20a using class Test20 from module test20
```
Changing from WARNING to INFO works and gives WARNING and INFO loggings.
Changing from WARNING to DEBUG gives WARNING and INFO loggings.

**Comment by ReneTode** [comment]
you set the log level from the main log (you use the main log in both apps)
so both apps influence the same log and that causes trouble.
if you want to set log level for a single app then you'll need to create seperate logs for both apps.

**Comment by skannea** [comment]
Yes it causes trouble.
You never get this behaviour with INFO and WARNING levels.
To me it looks like a bug.

**Comment by ReneTode** [comment]
you also get this behaviour with info and warning.
you CANT set 2 different loglevels for 1 log!
thats no bug, thats python.

**Comment by skannea** [comment]
The log_level may be specified for each app. I have no problems with INFO and WARNING.
And I guess it should work for DEBUG too, according to https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#writing-to-logfiles.

**Comment by ReneTode** [comment]
that will work if you use 2 or more different log files. not 1 logfile.

all logging is handled by https://docs.python.org/3/library/logging.html as far as i know.
and you cant set multiple levels for 1 log object for as far as i know.

if im mistaken then @Odianosen25 will correct me.
and indeed if im correct the docs are a little confusing.

**Comment by andjones132** [comment]
I am experiencing this same issue. INFO and WARNING log entries show up fine, but in order to see the DEBUG log entries via the web interface I have to hit F5 in order for the DEBUG entries to show up.

Here is my config:

log definition in appdaemon.yaml:
```
## Home Assistant Log Path
logs:
  main_log:
    filename: /config/appdaemon/logs/appdaemon.log
  access_log:
    filename: /config/appdaemon/logs/access.log
  error_log:
    filename: /config/appdaemon/logs/error.log
  diag_log:
    filename: /config/appdaemon/logs/diag.log
    log_generations: 5
    log_size: 1024
    format: "{asctime} {levelname:<8} {appname:<10}: {message}"
  app_log:
    filename: /config/appdaemon/logs/app.log
    name: Apps
    log_size: 1024
    format: "{asctime} {levelname:<8} {appname:<10}: {message}"```
```

apps.yaml module definition:
```
Shelly_Smart_Switch_Observatory:
  module: shelly_smart_switch
  class: Shelly_Smart_Switch
  friendly_name: Shelly Smart Button Observatory
  event_type: MQTT_MESSAGE
  mqtt_topic: shellies/buttons/shelly-button-obs/input_event/0
  action_actors:
    - S: light.office_desk_lamp
    - SS: none
    - SSS: none
    - L: light.office_desk_lamp
  log: app_log
  log_level: DEBUG
```

Using log leve in an applicatoin that uses Adbase:

These  log entries show up fine in the app_log in the web inteface:
```self.adapi.log(f"Listening to MQTT Topic {self.mqtt_topic}", level='INFO')```
```self.adapi.log(f"Listening to MQTT Topic {self.mqtt_topic}", level='WARNING')```

This log entry does not appear in the app_log in the web interface unless I it F5 to refresh the browser:
``self.adapi.log(f"Listening to MQTT Topic {self.mqtt_topic}", level='DEBUG')```

If have tried this using both Chrome and Firefox with the Cache cleared, but it didn't make any difference.
