### ISSUE TITLE
API Security documentation looks out of date?

### ISSUE THREAD

**Issue by foxy82** [AppDaemon/appdaemon#1491]
In the API Security documentation it talks about an api_key added to the `appdaemon:` section. 

https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#api-security

However I think this has now moved to the http component and been renamed to `password` as per the http config docs here:

https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuring-the-http-component

**Comment by Justihar** [comment]
You will want to use one or the other. The password option will password protect the web interface and the API. You will need to pass `x-ad-access` with the password as a header to access the API. I am pretty sure the api_password will only protect the API but not the web interface.

**Comment by foxy82** [comment]
Hmm something isn't working here.

Setting:
```yaml
appdaemon:
  api_password: something

http:
  url: http://127.0.0.1:5050

hadashboard:
admin:
api:
```

Lets me do a POST of http://<IP>:<PORT>//api/appdaemon/skill_name - without a password and I can see in the logs I start to process the request.

Setting:
```yaml
appdaemon:

http:
  url: http://127.0.0.1:5050
  password: something
hadashboard:
admin:
api:

```

does protect the API with the password but the admin page seems to be unprotected.

Also slightly annoyingly if I comment out the admin I end up with this screen
![image](https://user-images.githubusercontent.com/7756020/159757082-d55fcec5-0924-43b6-8b31-f2e297a21ea6.png)

It would be good to be able to supress this screen I'd rather not announce what I'm serving on this end point. I have to serve it externally to be able to use the alexa functionality.
