### ISSUE TITLE
unable to avoid call_service()  from escaping double quotes

### ISSUE THREAD

**Issue by caprageon** [AppDaemon/appdaemon#1610]
Hello,

I have a case of automation where i need to call "media_player/select_source" service and this specific target (AppleTV) awaits for certain source names to contain double quotes.

I tried escaping the quotes but the result is not as expected, not sure if it is related to my poor python skills or to an issue in call_service implementation..

Here a simplified version of my app :

```python
import hassapi as hass
"""
AppleTV
"""
class Atv(hass.Hass):
    def initialize(self):
        self.atv = "media_player.sejour"
        self.atv_services = {'inputs': {'input_button.atv_spotify': {'service': "Spotify"},
                                        'input_button.atv_series_tv': {'service': "\"Séries\_TV\""}}}
        self.listen_event(  self.event_button_press_c, 
                            "call_service", 
                            domaine = "input_button", 
                            service = "press")

    def event_button_press_c(self, event, data, kwargs):
        if data['service_data']['entity_id'] in self.atv_services['inputs'] :
            ent = data['service_data']['entity_id']
            self.log(ent)
            self.log(self.atv_services['inputs'][ent]['service'])
            self.call_service(  "media_player/select_source", 
                                entity_id = self.atv, 
                                source = self.atv_services['inputs'][ent]['service'])
```

Resulting event for Spotify : 

```yaml
event_type: call_service
data:
  domain: media_player
  service: select_source
  service_data:
    entity_id: media_player.sejour
    source: Spotify
origin: LOCAL
time_fired: "2022-11-29T12:37:51.744872+00:00"
context:
  id: 01GK1P9H00FYMAMXCRF7RPDJE3
  parent_id: null
  user_id: 80c3f69c6ffa4c5693672ae2917a36c4
```

Resulting event for "Séries\\_TV" :

```yaml
event_type: call_service
data:
  domain: media_player
  service: select_source
  service_data:
    entity_id: media_player.sejour
    source: "\"Séries\\_TV\""
origin: LOCAL
time_fired: "2022-11-29T12:37:56.751012+00:00"
context:
  id: 01GK1P9NWENE3Q6D1FPQFGYDQZ
  parent_id: null
  user_id: 80c3f69c6ffa4c5693672ae2917a36c4
```

It looks like call_service() is trying to escape the " and the \\ inside double quotes, which is redundant and I think should be done outside the call.

Expected result for "Séries\\_TV" (tested and working with standard HA automation):

<details>
<summary>input_atv_series_tv.yaml</summary>

![img](https://user-images.githubusercontent.com/9516349/204547949-f74e62d9-9ca8-4b2f-bfbf-2ca21795a781.png)
</details>

```yaml
event_type: call_service
data:
  domain: media_player
  service: select_source
  service_data:
    entity_id: media_player.sejour
    source: "Séries\_TV"
origin: LOCAL
time_fired: "2022-11-29T12:37:56.751012+00:00"
context:
  id: 01GK1P9NWENE3Q6D1FPQFGYDQZ
  parent_id: null
  user_id: 80c3f69c6ffa4c5693672ae2917a36c4
```

Here are the details of my install : 

> Home Assistant 2022.11.4 
> Supervisor 2022.11.2
> Operating System 9.3
> Interface utilisateur : 20221108.0 - latest 

> AppDaemon Current version: 0.10.1

Thanks in advance for your help !

Maxime.
