### ISSUE TITLE
How to change "available/unavailable" state for the Home Assistant entity?

### ISSUE THREAD

**Issue by Bagunda** [AppDaemon/appdaemon#1793]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Your feature request

I thought the state would change if set the state:

apps.yaml:
```yaml
light_center5:
  module: LightController
  class: LightController
  virt_light:
    - entity_id: light.virt_light_template1
```
LightController.py:
```yaml
self.virt_light = self.args["virt_light"][0]
self.set_state(self.virt_light["entity_id"], state = "on")
```

virt_light_template1 state changes in Home Assistant, but virt_light entity is not visible to AppDaemon.
As a result, the AppDaemon script is silent (does not write anything in the logs and does not execute the program)
