### ISSUE TITLE
Throw an error / refuse to load if apps.yaml has a duplicate top-level key

### ISSUE THREAD

**Issue by markfickett** [AppDaemon/appdaemon#1899]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Your feature request

A couple times I've accidentally repeated the same apps.yaml top-level key. AppDaemon picks one and ignores the other (maybe this is just YAML load behavior). This has led to confusing errors for me, such as a new app working fine but an old one no longer working somewhat mysteriously until I figure out what I did. I would rather AppDaemon treat this as an error and refuse to load the new apps.yaml file.

Example:

```yaml
my_app:
  module: my_app
  class: MyApp
  argument: value_one
# ... many lines ...
my_app:
  module: my_app
  class: MyApp
  argument: a_different_value
```

In the above case, I would like an error, but AppDaemon loads the file with only one `my_app`.

PyYAML has issues open for this since 2016 so I doubt we'll see a library solution, but [there are a number of workarounds mentioned](https://github.com/yaml/pyyaml/issues/165#issuecomment-430074049) like creating a customized loader.
