### ISSUE TITLE
allow multiple app_dir: 

### ISSUE THREAD

**Issue by palinf** [AppDaemon/appdaemon#2145]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Your feature request

In some cases two different directory needs to be declared as app_dir.

One case is when using addons installed with hacs, in the example controllerx

```
  app_dir: 
      - /config/apps #home made applications and code
      - /homeassistant/appdaemon/apps/controllerx #or /homeassistant/appdaemon/apps
```

**Comment by jsl12** [comment]
I looked at what this would actually take to implement, and unfortunately it would be pretty heavy duty because the `app_dir` is used in a ton of places, all of which would have to be modified to account for multiple values.

That said, I think there's an easy way to accomplish what you'd like to do. AppDaemon really only needs the app yaml files to be in the `app_dir`. The python files can actually live elsewhere. The only requirement is that they're importable. Files can be made importable by adding the appropriate path to the `appdaemon.import_paths` config key in `appdaemon.yaml`.

I'm not sure where HACS checks things out, but if you know where it is, you can add it like this:
```yaml
appdaemon:
  ... # rest of config
  import_paths:
    - <somewhere>/controllerx/apps/controllerx
```

This would allow you to use the modules, like in the `controllerx` [example](https://xaviml.github.io/controllerx/#quick-example):
```yaml
livingroom_controller:
  module: controllerx
  class: E2002LightController
  ... # rest of config
```
