### ISSUE TITLE
Allow Default action for icons

### ISSUE THREAD

**Issue by nbJosh** [AppDaemon/appdaemon#2146]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Your feature request

I have been trying to write this and get it to work all night,  

```
Hulu:
    title: "Hulu"
    widget_type: icon
    entity: sensor.nowplayingappletv
    widget_style: "background: #001f50;"
    state_text: ""
    widget_style: "background: #001f50;"
    icons:
        "Hulu":
            icon: mdi-hulu
            style: "color: #00e000"
        "default":
            style: "color: grey"
            icon: mdi-hulu
            post_service_active:
                service: homeassistant/turn_on
                entity_id: script.huluonappletv
```

However, I have found that post_service_active: is not called for the "default" condition!   
is this a bug?  or a feature request?
