### ISSUE TITLE
Failed to import, module not found

### ISSUE THREAD

**Issue by Tumetsu** [AppDaemon/appdaemon#2327]
### What happened?

I updated AppDaemon last night and I suppose 4.5 update broke something with my setup. Every app in my config now fails to load with listed error log saying its module could not be found.

For reference my appdaemon HA directory looks like this:
```
.
├── appdaemon.yaml
├── apps
│   ├── appliances
│   │   ├── air_humidifier.py
│   │   ├── ikea_shortcut_button.py
│   │   ├── __init__.py
│   │   ├── shield.py
│   │   └── turn_off_button.py
│   ├── automation_priority.py
│   ├── config
│   │   ├── apps.yaml
│   │   ├── __init__.py
│   │   ├── light_apps.yaml
│   │   └── motion_light_apps.yaml
│   ├── electricity.py
│   ├── __init__.py
│   ├── lights
│   │   ├── flux.py
│   │   ├── __init__.py
│   │   ├── motion_lights.py
│   │   ├── presence_lights.py
│   │   ├── priority_toggle.py
│   │   ├── switches
│   │   │   ├── ikea_onoff.py
│   │   │   ├── ikea_remote.py
│   │   │   ├── ikea_styrbar.py
│   │   │   └── __init__.py
│   │   └── wake_up_light.py
│   ├── __pycache__
│   └── utils.py
├── compiled
│   ├── css
│   └── javascript
├── dashboards
│   └── Hello.dash
├── __init__.py
├── logs -> ../../homeassistant/logs
├── namespaces
└── www
```

Sample from my `apps.yaml`:
```
---
priority:
  module: automation_priority
  class: Priority
  dependencies:
    - utils

flux:
  module: flux
  class: Flux
  dependencies:
    - priority
    - utils
  constrain_input_boolean: input_boolean.flux
  light_config:
    - id: light.makuuhuoneen_kattovalo
    - id: light.olohuoneen_kattovalot_group_2
    - id: light.olohuoneen_riippuvalaisin
      temp_modifier: -50
      brightness_modifier: -10
      min_supported_mireds: 100
    - id: light.olohuone_lednauha
    - id: light.olohuoneen_nymane_group
      temp_modifier: -50
      brightness_modifier: 10
      min_supported_mireds: 100
    - id: light.keittion_valot_group
    - id: light.eteisen_valot_group
      temp_modifier: 0
      brightness_modifier: 0
      min_supported_mireds: 100

nvidia_shield:
  module: shield
  class: Shield
  dependencies:
    - entities
  constrain_input_boolean: input_boolean.shield_light_control
  shield_id: media_player.shield
  light_ids_to_track:
    - light.olohuoneen_kattovalot_group_2
    - light.olohuone_lednauha
    - light.olohuoneen_nymane_group
  script_id: script.pimenna_pc_naytto

night_button:
  module: turn_off_button
  class: TurnOffForNightButton
  dependencies:
    - entities
    - utils
  button_ids:
    - xxx
  turn_off_ids:
    - light.kaikki_valot
    - media_player.home_group
    - media_player.kitchen_speaker
    - media_player.kitchen_speaker
  turn_on_ids:
    - script.suspend_pc
```

And `light_apps.yaml`:
```
olohuoneen_valokytkin:
  module: ikea_styrbar
  class: IkeaStyrbarFourway
  dependencies:
    - entities
    - utils
  switch_id: "xxx"
  light_id_top: light.olohuoneen_kattovalot_group_2
  light_id_bottom: light.tv_tason_kaappivalot
  light_id_right: light.olohuoneen_nymane_group
  light_id_left: light.olohuoneen_riippuvalaisin

olohuoneen_valokytkin2:
  module: ikea_styrbar
  class: IkeaStyrbarFourway
  dependencies:
    - entities
    - utils
  switch_id: "xxx"
  light_id_top: light.olohuoneen_kattovalot_group_2
  light_id_bottom: light.tv_tason_kaappivalot
  light_id_right: light.olohuoneen_nymane_group
  light_id_left: light.olohuoneen_riippuvalaisin
```

And my `turn_off_button.py` class:
```
from ikea_shortcut_button import IkeaShortcutButton


class TurnOffForNightButton(IkeaShortcutButton):

    def initialize(self):
        return super().initialize()

    def _delayed_turn_off(self, kwargs):
        self.turn_off(kwargs['entity_id'])

    def _on_press(self, event, data, kwargs):
        for idx, entity_id in enumerate(self.args['turn_off_ids']):
            self.run_in(self._delayed_turn_off, 1 * idx + 1, entity_id=entity_id)

        for entity_id in self.args['turn_on_ids']:
            self.turn_on(entity_id)
```

and its base class:
```
import appdaemon.plugins.hass.hassapi as hass
import utils


class IkeaShortcutButton(hass.Hass):
    """
    A base class for Ikea shortcut buttons
    Parameters:
    button_ids: device ids/names of the Ikea on/off switches as list
    """
    def initialize(self):
        self.click_event = 1002

        utils.subscribe_to_deconz_event(self, self._on_press, self.args['button_ids'], self.click_event)

    def _on_press(self, event, data, kwargs):
        pass
```

And my `appdaemon.yaml`:
```
---
secrets: /homeassistant/secrets.yaml
appdaemon:
  latitude: xxx
  longitude: xxx
  elevation: 2
  time_zone: Europe/Helsinki
  plugins:
    HASS:
      type: hass
      token: !env_var SUPERVISOR_TOKEN
http:
  url: http://0.0.0.0:5050
admin:
api:
hadashboard:
logs:
  main_log:
    filename: /homeassistant/logs/appdaemon.log
  access_log:
    filename: /homeassistant/logs/access.log
  error_log:
    filename: /homeassistant/logs/error.log
```

My guess is that the new importing system somehow broke in my setup and Appdaemon does not properly add the modules to the expected path `/config/apps`. Is there some problem with my directory structure? I tried to move my app modules to different places with no success. 

The error message is not that helpful since I'm not sure where the `config/apps` directory refers to. My guess is that it is the path where Appdaemon is supposed to add the python modules...?

Any help/ideas how to proceed?

### Version

4.5.3

### Installation type

Home Assistant add-on

### Relevant log output

```sh
2025-06-01 06:45:53.171707 ERROR Error: =====  Error importing 'turn_off_button'  =================================
2025-06-01 06:45:53.172369 ERROR Error: FailedImport: Failed to import 'turn_off_button'
2025-06-01 06:45:53.172532 ERROR Error:   Import paths:
2025-06-01 06:45:53.172689 ERROR Error:     /config/apps
2025-06-01 06:45:53.173693 ERROR Error:   ModuleNotFoundError: No module named 'turn_off_button'
```

### Relevant code in the app or config file that caused the issue

```sh

```

**Comment by jsl12** [comment]
This is just a result of the new app management/dependency system. I'm going to remove the bug tag, but leave the issue open for any discussion.

### Short Term

There's a couple fixes you can do right away to get moving again

#### Removing `__init__.py` Files (recommended)

Removing all the `__init__.py` files will also cause the `default` import method to add all those directories to your import path, and everything will work like it did before. It'll essentially make the imports work like the example in the [new docs](https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#imports).

#### Legacy Import Mode

This causes every directory under your `apps` directory to get added to the import path, which makes all your direct imports work like they did before.

```yaml
appdaemon:
  import_method: legacy
  ... # rest of config
```

### Long Term

There's going to be more to update in your code than this, but this is an explanation of what's going on with the new system and an example of how to fix things for the long term, based on your examples above:

Everything is fine with `ikea_shortcut_button.py` because the `apps` directory always gets added to the import path and the utils module is at `apps/utils.py`

```python
# apps/appliances/ikea_shortcut_button.py
import appdaemon.plugins.hass.hassapi as hass
import utils


class IkeaShortcutButton(hass.Hass):
    ...
```

However, the presence of `apps/appliances/__init__.py` changes things because it [indicates to python](https://docs.python.org/3/tutorial/modules.html#packages) that the files in that directory are part of a package. Files that want to use parts of the package therefore need to update their import lines. In the case of `turn_off_button.py`, it's part of the same package as `ikea_shortcut_button.py`, so it can use [relative imports](https://docs.python.org/3/reference/import.html#package-relative-imports) to reach it.

```python
# apps/appliances/turn_off_button.py
from .ikea_shortcut_button import IkeaShortcutButton


class TurnOffForNightButton(IkeaShortcutButton):
    ...
```

AppDaemon will now recognize this file dependency and any changes to `ikea_shortcut_button.py` will cause any apps based on `TurnOffForNightButton` to reload. It will also recognize the dependency between `ikea_shortcut_button.py` and `utils.py`, so that's no longer necessary to specify in the app config. The app config also needs to be updated to indicate that the module its using is part of a package.

```yaml
night_button:
  module: appliances.turn_off_button
  class: TurnOffForNightButton
  dependencies:
    - entities
  #   - utils
  ... # rest of config
```
