### ISSUE TITLE
HADashboard Icon widget is not vertically centered

### ISSUE THREAD

**Issue by e6on** [AppDaemon/appdaemon#767]
Icon widget is not vertically centered, when widget dimensions are small.
[https://community.home-assistant.io/t/icon-widget-is-not-centered/140789](url)
Example code:
```
title: Main Panel
widget_dimensions: [76, 68]
widget_size: [1, 1]
widget_margins: [4, 4]
columns: 16
global_parameters:
    use_comma: 0
    precision: 1
    use_hass_icon: 1
    dash_compile_on_start: 1
    dash_force_compile: 1
layout:
    - plant_moisture(1x1)
    - water_plant(1x1)

water_plant:
    widget_type: icon
    widget_style: "font-size: 20px;"
    icons:
      "0":
        icon: mdi-flower
        style: "color: lime;"
      "1":
        icon: mdi-flower
        style: "color: red"
    entity: sensor.water_plants_number
    
plant_moisture:
    widget_type: sensor
    widget_style: "font-size: 100%;"
    value_style: "color: aquamarine"
    unit_style: "color: aquamarine"
    precision: 0
    units: "%"
    entity: sensor.orhidee_moisture
```

**Comment by ReneTode** [comment]
yes you are right.
so you need to adjust the icon_style to make it like you want.
its almost impossible to give people the option to make appearance like they want and at the same time automaticly change positions and appearance based on some settings.

in AD the choice is made to give people the option to change the appearance yourselve.
so you can change the icon, the size of the icon, the place from the icon, the color of the icon, etc. all by adding some css.

**Comment by DaAwesomeP** [comment]
@e6on I was able to shift my icons up with a negative top margin:
```yaml
water_plant:
    widget_type: icon
    widget_style: "font-size: 20px;"
    icons:
      "0":
        icon: mdi-flower
        style: "color: lime; margin-top: -10px"
      "1":
        icon: mdi-flower
        style: "color: red; margin-top: -10px"
    entity: sensor.water_plants_number
```
