### ISSUE TITLE
AD 4: Camera widget

### ISSUE THREAD

**Issue by LaBoss** [AppDaemon/appdaemon#829]
Hello

After installing AD 4 I put the camera widget and so far so good!

The problem now is, if you restart HomeAssistant the IP of the tablet running Dashboard is banned!

I think it's because the camera token has changed and the dashboard didn't reflect this change!

Maybe it was better to detect if the HA was relinquished and force the camera token update

Thanks

Version | 4.0.0b2

**Comment by ReneTode** [comment]
dashboard cant know that you restart HA, and even if we modify dashboard so that the HA start event is noticed and all dashboards automaticly get reconnected, we get the same trouble as with apps. HA gives its events before all components are completely setup.
so the risk is that at that point a lot of widgets get an error because entities are not setup when the dashboard is loaded.

the best way to go is to set the dashboard in HA as trusted, so it wont get banned.

and create automations that the dashboards are reloaded some time after HA has been restarted.

**Comment by LaBoss** [comment]
Its not possible handle 403 error when token got invalid first time?

Is there any api that can force dashboards to reload?

Thanks for reply

**Comment by ReneTode** [comment]
there is no api that forces dashboards to reload.
you can add headscripts to a skin to handle that, or like i do: use fully kiosk and use that to reload the dashboards.

i dont know how the widget should check for the 403 error.
but at that point its already to late, because dashboard would only change the token after it would have tried to logon with an invalid token, and then its blocked.

making sure that HA just never blocks your dashboard is the easiest way.

**Comment by ajitam** [comment]
@ReneTode I'm trying to whitelist my dashboards to bypass this problem with 

```
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.29.3/32
        - 192.168.29.6/32
```

but they are still getting banned. Am I missing something?

**Comment by ReneTode** [comment]
i dont know.
how is the camera setup in your dashboard?

**Comment by ajitam** [comment]
well camera is set like this 

```
camera:
  widget_type: camera
  entity: camera.bedroom
  base_url: https://url.to.ha.cm
  refresh: 1
```


I thought this was just a matter of whitelisting IP of the tablet showing dashboard
