### ISSUE TITLE
After the upgrade to 4.0, the dialogflow integration stopped working

### ISSUE THREAD

**Issue by bruxy70** [AppDaemon/appdaemon#863]
# Problem/Motivation

I have an app to handle dialogflow callbacks. It stopped working after the update. 
I have hass.io with Appdaemon 4 0.1.2 add-on.

## Actual behavior

The dialogflow says that it cannot connect to Home Assistant. In the diagnostics it shows 
```
"webhookStatus": {
    "code": 4,
    "message": "Webhook call failed. Error: DEADLINE_EXCEEDED."
  }
```

In all debug log, it initialize the class, but the api_callback is not called.
Originally, the application class was called Dialogflow, and in the class init I have been registering the endpoint: `self.register_endpoint(self.dialogflow_callback, "dialogflow")`
Reading the documentation, I have renamed the class to `Apiai`, renamed the callback to `api_call` and removed the callback registration in initialize, replaced with `pass`, but it still does not work (the first line in the callback function is `self.log(data, level="INFO")`, but it does not show up.

It used to work before (I did have own code to support response, intent and parameters for API v2, but as part of throubleshooting I also removed that and replaced with what is in the documentation - anyhow, the callback is not even called, so this is not an issue.

I have tried to add the self.register_endpoint back, pointing to api_call, but that does not work either.

## Steps to reproduce

In the dialogflow fulfillment I have registered url:
`https://<my domain>:5050/api/appdaemon/dialogflow`
with `x-ad-access`, that is configured in `appdaemon.yaml` api_key:
```yaml
appdaemon:
  latitude: <redacted>
  longitude: <redacted>
  elevation: <redacted>
  time_zone: Europe/Prague
  api_ssl_certificate: /ssl/fullchain.pem
  api_ssl_key: /ssl/privkey.pem
  api_key: <redacted>
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
admin:
api:
```
(I have also tried to changed the url to https, but that did not help.

I have 5050 routed to Home Assistant (it worked before, so that works).

And the application is registered this way:
```yaml
dialogflow:
    module: dialogflow
    class: Apiai
```

## Proposed changes

An example (template) of tested dialogflow application would be nice.

**Comment by ReneTode** [comment]
you try to use a https url and you didnt setup appdaemon.yaml correct for that.
```
  api_ssl_certificate: /ssl/fullchain.pem
  api_ssl_key: /ssl/privkey.pem
  api_key: <redacted>
```
were used in AD 3 but they dont work in AD 4

the docs for api use:
https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuring-the-api

tell you that api doesnt have arguments and SSL and password are setup in the http section

https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuring-the-http-component

so you need to set http and pasword in the http section if you want to use an api call with ssl and password.

renaming the class or callback wont have any effect.

**Comment by bruxy70** [comment]
Thanks for quick response.
But the doc contains `api_ssl_certificate` and key:
https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuration-of-the-hass-plugin

Anyhow, I have changed the config this way, and it still does not work:
```yaml
appdaemon:
  latitude: <redacted>
  longitude: <redacted>
  elevation: <redacted>
  time_zone: Europe/Prague
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
  password: <redacted>
  dash_ssl_certificate: /ssl/fullchain.pem
  dash_ssl_key: /ssl/privkey.pem
admin:
api:
```
The way I read the documentation, the certificates in the http section are for the dashboard (that I do not use). Dialogflow needs https for the api.
