### ISSUE TITLE
SSL support for dashboards

### ISSUE THREAD

**Issue by tazmad** [AppDaemon/appdaemon#994]
Hi there,

Apologies if I am opening a duplicate issue, but the other one that references this problem seems to be related to another topic (#863), the only one that references SSL is closed (#851), but I am having a problem getting HADashboard to load using SSL.  My configuration has:

```
  appdaemon:
    plugins:
      HASS:
        type: hass
    latitude: 5.5
    longitude: 0.0
    elevation: 1
    time_zone: Europe/London
  http:
    url: http://127.0.0.1:5050
    dash_ssl_certifiacate: /ssl/fullchain.pem
    dash_ssl_key: /ssl/privkey.pem
  hadashboard:
  admin:
  api:
```

I see no errors on the appdaemon logs, but am unable to establish a secure connection to the server:

```
user@mac ~ % curl -vvo- https://hassio.local.com:5050/
*   Trying 192.168.24.70...
* TCP_NODELAY set
* Connected to hassio.local.com (192.168.24.70) port 5050 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
```
And just hangs at this point.  Any suggestions on trying to get this resolved?
